// Generated by CoffeeScript 1.6.3
var Event, History,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Event = require('happens');

module.exports = History = (function(_super) {
  __extends(History, _super);

  History.prototype.history = window.history;

  function History(base_path) {
    var _this = this;
    this.base_path = base_path;
    window.addEventListener('popstate', function() {
      return _this.emit('url:change', _this.pathname());
    }, false);
  }

  History.prototype.pathname = function() {
    var address, index;
    if (!this.base_path) {
      console.warn("doesnt have base_path");
      return window.location.pathname;
    } else {
      index = String(window.location.pathname).indexOf(this.base_path);
      address = String(window.location.pathname).substr(index);
      return address = address.replace(this.base_path, '');
    }
  };

  History.prototype.push = function(url, title, state) {
    window.history.pushState(state, title, url);
    if (title != null) {
      document.title = title;
    }
    return this.emit('url:change', window.location.pathname);
  };

  History.prototype.replace = function(url, title, state) {
    window.history.replaceState(state, title, url);
    if (title != null) {
      return document.title = title;
    }
  };

  return History;

})(Event);
